CREATE TABLE covid_vaccinations (
    id INT AUTO_INCREMENT PRIMARY KEY,
    iso_code VARCHAR(3),
    continent VARCHAR(50),
    location VARCHAR(50),
    date DATE,
    new_tests INT,
    total_tests INT,
    total_tests_per_thousand DECIMAL(10, 3),
    new_tests_per_thousand DECIMAL(10, 3),
    new_tests_smoothed INT,
    new_tests_smoothed_per_thousand DECIMAL(10, 3),
    positive_rate DECIMAL(10, 3),
    tests_per_case DECIMAL(10, 3),
    tests_units VARCHAR(50),
    total_vaccinations INT,
    people_vaccinated INT,
    people_fully_vaccinated INT,
    new_vaccinations INT,
    new_vaccinations_smoothed INT,
    total_vaccinations_per_hundred DECIMAL(10, 3),
    people_vaccinated_per_hundred DECIMAL(10, 3),
    people_fully_vaccinated_per_hundred DECIMAL(10, 3),
    new_vaccinations_smoothed_per_million INT,
    stringency_index DECIMAL(10, 2),
    population_density DECIMAL(10, 3),
    median_age DECIMAL(10, 2),
    aged_65_older DECIMAL(10, 3),
    aged_70_older DECIMAL(10, 3),
    gdp_per_capita DECIMAL(15, 3),
    extreme_poverty DECIMAL(5, 2),
    cardiovasc_death_rate DECIMAL(10, 3),
    diabetes_prevalence DECIMAL(5, 2),
    female_smokers DECIMAL(5, 2),
    male_smokers DECIMAL(5, 2),
    handwashing_facilities DECIMAL(10, 3),
    hospital_beds_per_thousand DECIMAL(5, 2),
    life_expectancy DECIMAL(10, 3),
    human_development_index DECIMAL(5, 3)
);
ALTER TABLE covid_vaccinations
MODIFY COLUMN iso_code VARCHAR(50);

CREATE TABLE covid_deaths (
    id INT AUTO_INCREMENT PRIMARY KEY,
    iso_code VARCHAR(50) NOT NULL,
    continent VARCHAR(50),
    location VARCHAR(100) NOT NULL,
    date DATE NOT NULL,
    total_cases INT,
    new_cases INT,
    new_cases_smoothed DECIMAL(10, 3),
    total_deaths INT,
    new_deaths INT,
    new_deaths_smoothed DECIMAL(10, 3),
    total_cases_per_million DECIMAL(15, 3),
    new_cases_per_million DECIMAL(15, 3),
    new_cases_smoothed_per_million DECIMAL(15, 3),
    total_deaths_per_million DECIMAL(15, 3),
    new_deaths_per_million DECIMAL(15, 3),
    new_deaths_smoothed_per_million DECIMAL(15, 3),
    reproduction_rate DECIMAL(5, 2),
    icu_patients INT,
    icu_patients_per_million DECIMAL(15, 3),
    hosp_patients INT,
    hosp_patients_per_million DECIMAL(15, 3),
    weekly_icu_admissions DECIMAL(10, 3),
    weekly_icu_admissions_per_million DECIMAL(15, 3),
    weekly_hosp_admissions DECIMAL(15, 3),
    weekly_hosp_admissions_per_million DECIMAL(15, 3),
    new_tests INT,
    total_tests INT,
    total_tests_per_thousand DECIMAL(15, 3),
    new_tests_per_thousand DECIMAL(15, 3),
    new_tests_smoothed INT,
    new_tests_smoothed_per_thousand DECIMAL(15, 3),
    positive_rate DECIMAL(5, 3),
    tests_per_case FLOAT,
    tests_units VARCHAR(100),
    total_vaccinations INT,
    people_vaccinated INT,
    people_fully_vaccinated INT,
    new_vaccinations INT,
    new_vaccinations_smoothed INT,
    total_vaccinations_per_hundred DECIMAL(15, 3),
    people_vaccinated_per_hundred DECIMAL(15, 3),
    people_fully_vaccinated_per_hundred DECIMAL(15, 3),
    new_vaccinations_smoothed_per_million DECIMAL(15, 3),
    stringency_index DECIMAL(10, 2),
    population BIGINT,
    population_density DECIMAL(10, 3),
    median_age DECIMAL(5, 1),
    aged_65_older DECIMAL(5, 3),
    aged_70_older DECIMAL(5, 3),
    gdp_per_capita DECIMAL(15, 3),
    extreme_poverty DECIMAL(5, 2),
    cardiovasc_death_rate DECIMAL(15, 3),
    diabetes_prevalence DECIMAL(5, 2),
    female_smokers DECIMAL(5, 1),
    male_smokers DECIMAL(5, 1),
    handwashing_facilities DECIMAL(10, 3),
    hospital_beds_per_thousand DECIMAL(5, 2),
    life_expectancy DECIMAL(5, 2),
    human_development_index DECIMAL(5, 3)
);

ALTER TABLE covid_deaths
MODIFY COLUMN total_cases INT;